#!/bin/bash

function usage {
  cat <<EOM
Usage: $(basename "$0") [OPTION]
  -h          Display help
  -m          Mount EFI
  -u          Unmount EFI
  nothong     Exit
EOM

  exit 2
}
while getopts "muhx" GO
do
  case $GO in
    m)
sudo diskutil mount /dev/disk0s1
      ;;
    u)
sudo diskutil unmount /dev/disk0s1
      ;;
'-h'|'--help'|* )
echo
echo "      DoEFI 1.0"
echo
      usage
      ;;
  esac
done